### ISSUE TITLE
Worker mode

### ISSUE THREAD

**Issue by cvladan** [StephenMiracle/frankenwp#31]
Thank you for your efforts on this project!
It's an amazing idea, and I hope FrankenPHP will work well with WordPress.

I've been looking through the repository, but I'm having trouble determining if this is designed to work in worker mode.

The only mention I found of worker mode is in the Caddyfile:
https://github.com/StephenMiracle/frankenwp/blob/e05bcc3d951dc57636c87befa63357ec1350006d/Caddyfile#L7

Could you please clarify if this project is intended to function in worker mode, and if it has been tested in that environment?

I'd appreciate any additional information you can provide on this aspect of the project - the suggested value of $FRANKENPHP_CONFIG for a worker mode.

Thanks again!

**Comment by PascaleBeier** [comment]
Hey, due to the architecture of WordPress it's not possible to use worker mode in WordPress at all. It requires specific patches of the WordPress Core to Request / Response lifecycles.

You can read more about that here: https://github.com/WordPress-PSR/swoole, specifically https://github.com/WordPress-PSR/request-handler/

**Comment by cvladan** [comment]
Thanks!
